groups:
  - name: microservices_health
    rules:
      - alert: MicroserviceDown
        expr: probe_success == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Microservicio ca√≠do: {{ $labels.instance }}"
          description: "El microservicio {{ $labels.instance }} no responde al health check."
